const h = [{
        label: 'CPU',
        options: [{
                hardwareId: '0',
                label: 'CPU only - 2 vCPU - 16 GiB',
                label_short: '2 vCPU · 16 GiB RAM',
                price: 'Free',
                type: 'C1ae.small',
                vCPU: '2',
                typeLabel: 'CPU',
                paid: '0',
                memory: 16,
                pricePerHour: 0
            },
            {
                hardwareId: '1',
                label: 'CPU only - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB RAM',
                price: '1 LAG per hour',
                type: 'C1ae.medium',
                vCPU: '8',
                typeLabel: 'CPU',
                paid: '1',
                memory: 32,
                pricePerHour: 360000000000000000
            },
        ],
        options_setting: []
    },
    {
        label: 'GPU',
        options: [{
                hardwareId: '2',
                label: 'Nvidia 2060 - 4 vCPU - 16 GiB',
                label_short: '4 vCPU · 16 GiB · Nvidia 2060',
                price: '2 LAG per hour',
                type: 'M1ae.small',
                vCPU: '4',
                typeLabel: 'GPU',
                paid: '2',
                memory: 16,
                pricePerHour: 1494000000000000000
            }, {
                hardwareId: '3',
                label: 'Nvidia 2060 - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia 2060',
                price: '4 LAG per hour',
                type: 'M1ae.medium',
                vCPU: '8',
                typeLabel: 'GPU',
                paid: '4',
                memory: 32,
                pricePerHour: 2988000000000000000
            }, {
                hardwareId: '4',
                label: 'Nvidia 2080 Ti - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia 2080 Ti',
                price: '6 LAG per hour',
                type: 'M1ae.large',
                vCPU: '8',
                typeLabel: 'GPU',
                paid: '6',
                memory: 32,
                pricePerHour: 2988000000000000000
            },
            {
                hardwareId: '5',
                label: 'Nvidia 3060 Ti - 4 vCPU - 16 GiB',
                label_short: '4 vCPU · 16 GiB · Nvidia 3060 Ti',
                price: '7 LAG per hour',
                type: 'M2ae.small',
                vCPU: '4',
                typeLabel: 'GPU',
                paid: '7',
                memory: 16,
                pricePerHour: 3492000000000000000
            },
            {
                hardwareId: '6',
                label: 'Nvidia 3060 Ti - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia 3060 Ti',
                price: '8 LAG per hour',
                type: 'M2ae.medium',
                vCPU: '8',
                typeLabel: 'GPU',
                paid: '8',
                memory: 32,
                pricePerHour: 7002000000000000000
            },
            {
                hardwareId: '7',
                label: 'Nvidia 3070 - 4 vCPU - 16 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia 3070',
                price: '9 LAG per hour',
                type: 'M2ae.large',
                vCPU: '4',
                typeLabel: 'GPU',
                paid: '9',
                memory: 16,
                pricePerHour: 7002000000000000000
            },
            {
                hardwareId: '8',
                label: 'Nvidia 3070 Ti - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia 3070 Ti',
                price: '10 LAG per hour',
                type: 'M2ae.xlarge',
                vCPU: '8',
                typeLabel: 'GPU',
                paid: '10',
                memory: 32,
                pricePerHour: 7002000000000000000
            },
            {
                hardwareId: '9',
                label: 'Nvidia 3080 - 4 vCPU - 16 GiB',
                label_short: '4 vCPU · 16 GiB · Nvidia 3080',
                price: '11 LAG per hour',
                type: 'G1ae.small',
                vCPU: '4',
                typeLabel: 'GPU',
                paid: '11',
                memory: 16,
                pricePerHour: 4500000000000000000
            },
            {
                hardwareId: '10',
                label: 'Nvidia 3080 - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia 3080',
                price: '13 LAG per hour',
                type: 'G1ae.medium',
                vCPU: '8',
                typeLabel: 'GPU',
                paid: '13',
                memory: 32,
                pricePerHour: 7488000000000000000
            },
            {
                hardwareId: '11',
                label: 'Nvidia 3080 Ti - 4 vCPU - 16 GiB',
                label_short: '4 vCPU · 16 GiB · Nvidia 3080 Ti',
                price: '15 LAG per hour',
                type: 'G1ae.large',
                vCPU: '4',
                typeLabel: 'GPU',
                paid: '15',
                memory: 16,
                pricePerHour: 5490000000000000000
            },
            {
                hardwareId: '12',
                label: 'Nvidia 3080 Ti - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia 3080 Ti',
                price: '18 LAG per hour',
                type: 'G1ae.xlarge',
                vCPU: '8',
                typeLabel: 'GPU',
                paid: '18',
                memory: 32,
                pricePerHour: 7992000000000000000
            },
            {
                hardwareId: '13',
                label: 'Nvidia T4 - 4 vCPU - 16 GiB',
                label_short: '4 vCPU · 16 GiB · Nvidia T4',
                price: '20 LAG per hour',
                type: 'G2ae.small',
                vCPU: '4',
                typeLabel: 'GPU',
                paid: '20',
                memory: 16,
                pricePerHour: 5994000000000000000
            },
            {
                hardwareId: '14',
                label: 'Nvidia T4 - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia T4',
                price: '23 LAG per hour',
                type: 'G2ae.medium',
                vCPU: '8',
                typeLabel: 'GPU',
                paid: '23',
                memory: 32,
                pricePerHour: 9000000000000000000
            },
            {
                hardwareId: '15',
                label: 'Nvidia A10G - 4 vCPU - 16 GiB',
                label_short: '4 vCPU · 16 GiB · Nvidia A10G',
                price: '26 LAG per hour',
                type: 'G2ae.large',
                vCPU: '4',
                typeLabel: 'GPU',
                paid: '26',
                memory: 16,
                pricePerHour: 10494000000000000000
            },
            {
                hardwareId: '16',
                label: 'Nvidia A10G - 12 vCPU - 48 GiB',
                label_short: '12 vCPU · 48 GiB · Nvidia A10G',
                price: '28 LAG per hour',
                type: 'G2ae.lxarge',
                vCPU: '12',
                typeLabel: 'GPU',
                paid: '28',
                memory: 48,
                pricePerHour: 31500000000000000000
            },
            {
                hardwareId: '17',
                label: 'Nvidia 3090 - 4 vCPU - 16 GiB',
                label_short: '4 vCPU · 16 GiB · Nvidia 3090',
                price: '30 LAG per hour',
                type: 'Hpc1ae.small',
                vCPU: '4',
                typeLabel: 'GPU',
                paid: '30',
                memory: 16,
                pricePerHour: 12492000000000000000
            },
            {
                hardwareId: '18',
                label: 'Nvidia 3090 - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia 3090',
                price: '32 LAG per hour',
                type: 'Hpc1ae.medium',
                vCPU: '8',
                typeLabel: 'GPU',
                paid: '32',
                memory: 32,
                pricePerHour: 24984000000000000000
            },
            {
                hardwareId: '19',
                label: 'Nvidia 3090 Ti - 4 vCPU - 16 GiB',
                label_short: '4 vCPU · 16 GiB · Nvidia 3090 Ti',
                price: '34 LAG per hour',
                type: 'Hpc1ae.large',
                vCPU: '4',
                typeLabel: 'GPU',
                paid: '34',
                memory: 16,
                pricePerHour: 13500000000000000000
            },
            {
                hardwareId: '20',
                label: 'Nvidia 3090 Ti - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia 3090 Ti',
                price: '36 LAG per hour',
                type: 'Hpc1ae.xlarge',
                vCPU: '8',
                typeLabel: 'GPU',
                paid: '36',
                memory: 32,
                pricePerHour: 25992000000000000000
            },
            {
                hardwareId: '21',
                label: 'Nvidia 4090 - 4 vCPU - 16 GiB',
                label_short: '4 vCPU · 16 GiB · Nvidia 4090',
                price: '38 LAG per hour',
                type: 'Hpc2ae.small',
                vCPU: '4',
                typeLabel: 'GPU',
                paid: '38',
                memory: 16,
                pricePerHour: 14994000000000000000
            },
            {
                hardwareId: '22',
                label: 'Nvidia 4090 - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia 4090',
                price: '40 LAG per hour',
                type: 'Hpc2ae.medium',
                vCPU: '8',
                typeLabel: 'GPU',
                paid: '40',
                memory: 32,
                pricePerHour: 25380000000000000000
            },
            {
                hardwareId: '23',
                label: 'Nvidia 4090 Ti - 4 vCPU - 16 GiB',
                label_short: '4 vCPU · 16 GiB · Nvidia 4090 Ti',
                price: '42 LAG per block',
                type: 'Hpc2ae.large',
                vCPU: '4',
                typeLabel: 'GPU',
                paid: '42',
                memory: 16,
                pricePerHour: 16992000000000000000
            },
            {
                hardwareId: '24',
                label: 'Nvidia 4090 Ti - 8 vCPU - 32 GiB',
                label_short: '8 vCPU · 32 GiB · Nvidia 4090 Ti',
                price: '44 LAG per hour',
                type: 'Hpc2ae.xlarge',
                vCPU: '8',
                typeLabel: 'GPU',
                paid: '44',
                memory: 32,
                pricePerHour: 28998000000000000000
            },
            {
                hardwareId: '25',
                label: 'Nvidia A100 - 12 vCPU - 128 GiB',
                label_short: '12 vCPU · 128 GiB · Nvidia A100',
                price: '46 LAG per hour',
                type: 'P1ae.small',
                vCPU: '12',
                typeLabel: 'GPU',
                paid: '46',
                memory: 128,
                pricePerHour: 41292000000000000000
            },
            {
                hardwareId: '26',
                label: 'Nvidia A100 - 24 vCPU - 256 GiB',
                label_short: '24 vCPU · 256 GiB · Nvidia A100',
                price: '52 LAG per hour',
                type: 'P1ae.medium',
                vCPU: '24',
                typeLabel: 'GPU',
                paid: '52',
                memory: 256,
                pricePerHour: 99990000000000000000
            },
            {
                hardwareId: '27',
                label: 'Nvidia H100 - 12 vCPU - 128 GiB',
                label_short: '12 vCPU · 128 GiB · Nvidia H100',
                price: '57 LAG per hour',
                type: 'P1ae.large',
                vCPU: '12',
                typeLabel: 'GPU',
                paid: '57',
                memory: 128,
                pricePerHour: 52992000000000000000
            },
            {
                hardwareId: '28',
                label: 'Nvidia H100 - 24 vCPU - 256 GiB',
                label_short: '24 vCPU · 256 GiB · Nvidia H100',
                price: '65 LAG per hour',
                type: 'P1ae.xlarge',
                vCPU: '24',
                typeLabel: 'GPU',
                paid: '65',
                memory: 256,
                pricePerHour: 137988000000000000000
            },
        ],
        options_setting: []
    },
]
export default h